services:
  - type: web
    name: resanalyzer-backend
    env: docker
    region: ohio
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: ENVIRONMENT
        value: production
    envGroups:
      - akhil
